### ISSUE TITLE
Join mail list scroll

### ISSUE THREAD

**Issue by Siizumi** [MikeChipshop/PB#57]
The 'signup to mail list' bar is currently sitting at the foot of each page, meaning that it's only visible when the visitor has scrolled to the foot of any page, whereas previously, it was present at the foot regardless of where you were content-wise. Can that be added as a standard? That way, people will be more inclined to deal with it one way of the other, being that it's omnipresent.

**Comment by MikeChipshop** [comment]
Bar "Floats" to bottom unless otherwise dismissed by user. If user clicks 'close' ( X ) button, the bar relocates to the bottom of the page (rather than screen). This is by design to stop it hogging valuable screen real estate unless it is actually wanted.

To be clear, all new users (and old users visiting on new machines) will see the bar floating at the bottom of the screen.
